// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: prime.proto

package primenumber

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PrimeNumberStreaming struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeNumberStreaming) Reset() {
	*x = PrimeNumberStreaming{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberStreaming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberStreaming) ProtoMessage() {}

func (x *PrimeNumberStreaming) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberStreaming.ProtoReflect.Descriptor instead.
func (*PrimeNumberStreaming) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeNumberStreaming) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeNumberStreamingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *PrimeNumberStreaming `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *PrimeNumberStreamingRequest) Reset() {
	*x = PrimeNumberStreamingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberStreamingRequest) ProtoMessage() {}

func (x *PrimeNumberStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberStreamingRequest.ProtoReflect.Descriptor instead.
func (*PrimeNumberStreamingRequest) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeNumberStreamingRequest) GetRequest() *PrimeNumberStreaming {
	if x != nil {
		return x.Request
	}
	return nil
}

type PrimeNumberStreamingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response int64 `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PrimeNumberStreamingResponse) Reset() {
	*x = PrimeNumberStreamingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberStreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberStreamingResponse) ProtoMessage() {}

func (x *PrimeNumberStreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberStreamingResponse.ProtoReflect.Descriptor instead.
func (*PrimeNumberStreamingResponse) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeNumberStreamingResponse) GetResponse() int64 {
	if x != nil {
		return x.Response
	}
	return 0
}

var File_prime_proto protoreflect.FileDescriptor

var file_prime_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x5a, 0x0a, 0x1b, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x1c, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x90, 0x01, 0x0a, 0x1b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x71, 0x0a, 0x18, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28,
	0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_proto_rawDescOnce sync.Once
	file_prime_proto_rawDescData = file_prime_proto_rawDesc
)

func file_prime_proto_rawDescGZIP() []byte {
	file_prime_proto_rawDescOnce.Do(func() {
		file_prime_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_proto_rawDescData)
	})
	return file_prime_proto_rawDescData
}

var file_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_prime_proto_goTypes = []interface{}{
	(*PrimeNumberStreaming)(nil),         // 0: primenumber.PrimeNumberStreaming
	(*PrimeNumberStreamingRequest)(nil),  // 1: primenumber.PrimeNumberStreamingRequest
	(*PrimeNumberStreamingResponse)(nil), // 2: primenumber.PrimeNumberStreamingResponse
}
var file_prime_proto_depIdxs = []int32{
	0, // 0: primenumber.PrimeNumberStreamingRequest.request:type_name -> primenumber.PrimeNumberStreaming
	1, // 1: primenumber.PrimeNumberStreamingService.PrimeNumberDecomposition:input_type -> primenumber.PrimeNumberStreamingRequest
	2, // 2: primenumber.PrimeNumberStreamingService.PrimeNumberDecomposition:output_type -> primenumber.PrimeNumberStreamingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prime_proto_init() }
func file_prime_proto_init() {
	if File_prime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberStreaming); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberStreamingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberStreamingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_proto_goTypes,
		DependencyIndexes: file_prime_proto_depIdxs,
		MessageInfos:      file_prime_proto_msgTypes,
	}.Build()
	File_prime_proto = out.File
	file_prime_proto_rawDesc = nil
	file_prime_proto_goTypes = nil
	file_prime_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeNumberStreamingServiceClient is the client API for PrimeNumberStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberStreamingServiceClient interface {
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberStreamingRequest, opts ...grpc.CallOption) (PrimeNumberStreamingService_PrimeNumberDecompositionClient, error)
}

type primeNumberStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeNumberStreamingServiceClient(cc grpc.ClientConnInterface) PrimeNumberStreamingServiceClient {
	return &primeNumberStreamingServiceClient{cc}
}

func (c *primeNumberStreamingServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberStreamingRequest, opts ...grpc.CallOption) (PrimeNumberStreamingService_PrimeNumberDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberStreamingService_serviceDesc.Streams[0], "/primenumber.PrimeNumberStreamingService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberStreamingServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberStreamingService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberStreamingResponse, error)
	grpc.ClientStream
}

type primeNumberStreamingServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *primeNumberStreamingServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberStreamingResponse, error) {
	m := new(PrimeNumberStreamingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberStreamingServiceServer is the server API for PrimeNumberStreamingService service.
type PrimeNumberStreamingServiceServer interface {
	PrimeNumberDecomposition(*PrimeNumberStreamingRequest, PrimeNumberStreamingService_PrimeNumberDecompositionServer) error
}

// UnimplementedPrimeNumberStreamingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberStreamingServiceServer struct {
}

func (*UnimplementedPrimeNumberStreamingServiceServer) PrimeNumberDecomposition(*PrimeNumberStreamingRequest, PrimeNumberStreamingService_PrimeNumberDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomposition not implemented")
}

func RegisterPrimeNumberStreamingServiceServer(s *grpc.Server, srv PrimeNumberStreamingServiceServer) {
	s.RegisterService(&_PrimeNumberStreamingService_serviceDesc, srv)
}

func _PrimeNumberStreamingService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberStreamingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberStreamingServiceServer).PrimeNumberDecomposition(m, &primeNumberStreamingServicePrimeNumberDecompositionServer{stream})
}

type PrimeNumberStreamingService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberStreamingResponse) error
	grpc.ServerStream
}

type primeNumberStreamingServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *primeNumberStreamingServicePrimeNumberDecompositionServer) Send(m *PrimeNumberStreamingResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberStreamingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primenumber.PrimeNumberStreamingService",
	HandlerType: (*PrimeNumberStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _PrimeNumberStreamingService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime.proto",
}
